### ISSUE TITLE
flow_from_dataframe too slow

### ISSUE THREAD

**Issue by qinst64** [keras-team/keras-preprocessing#171]
I am running the latest version aka __Keras-Preprocessing==1.0.9__ on around 150K images.
the __flow_from_directory__ takes <6s to init whereas __flow_from_dataframe__ takes >30s.

After testing the source code, the line  
```
existence_check = filepaths.map(os.path.isfile)
``` 

is consuming almost all the time. This is a known issue of file check as I  [google it](https://www.google.com/search?q=os.path.isfile%20slow)

After removing the ___filter_valid_filepaths__ (i.e. format_check & existence_check) my code takes < 0.5s.

Any methods to speed up?

If not, a switch for users might be a solution(I am pretty sure all the files in my dataframe  are valid files and  not directories.). thx

**Comment by Dref360** [comment]
So I guess that the way to solve that is to group the paths by their parent folder, call listdir on that folder and compare both list. Would be much faster.

I'll try to submit a PR over the weekend.

**Comment by jkthompson** [comment]
I just ran into the same issue as @qinst64.  In my case I'm working with a directory of over 1 million images on a file system with poor latency, and a directory hierarchy several levels deep.  I'm concerned that listing all files in the directory could also be slow, especially if my dataframe only contains a small fraction of the images in the directory.  In my view, it would be nice to have the option to turn off image validation.  Maybe the generator could catch & skip invalid images at generation time?  Would be happy to help with testing.

**Comment by rragundez** [comment]
I haven't looked at the code specifically but it sounds to me that the best solution will be to:

- use glob.iglob if directory is given. This will be faster and avoid the memory footprint of listing all paths. Also remember to use iglob since we need a generator and glob.glob in python 2.7 returns a list. 
- Keep current behavior if no directory is given. If no directory is given the images could be coming from different directories. 

This difference should be documented to the use stating that it is preferred to give a directory parameter if all images are coming from the same directory.

As a side note we can also restrict the API and force the user to always use a directory parameter, so forcing the user to always have the images in the same directory.

**Comment by Dref360** [comment]
Couldn't just set '/' as the directory and then we need to glob the entire hard drive?

Unfortunatly, I was not able to work on this over the weekend. Will do my best to finish this over the week.

**Comment by rragundez** [comment]
I don't understand the question. What the directory parameters is, is up to the user. I was just mentioning that instead of listdir you do glob in your idea, you only address those subdirecttories mentioned in the filenames column.

**Comment by jkthompson** [comment]
I just took a look at how _**filter_valid_filepaths** works.  As I understand, it silently filters out samples that don't exist or that have unsupported extensions.  As a user, I would expect a warning if the input data is modified like this.  It would most likely point to an error in constructing the filenames that I would want to correct.  I also question if this filter should be strictly required.  I would propose:
1) add a 'validate_images' flag so users can turn the filter on or off
2) if 'validate_images' is True, run the filter and print a warning if there are missing or unsupported samples 
Finally, 'listdir' may not be faster in all cases, as is pointed out in the google link posted by @qinst64, specifically in cases where there are many more files in the directory than in the dataframe.

**Comment by Dref360** [comment]
Sorry @rragundez I misread.

In any case, I tried the suggestion mentioned above and it is slow.

I agree with @jkthompson that the validation should be up to the user.

**Comment by rragundez** [comment]
@qinst64 do you have a minimal reproducible example? 
I made this little test with 270000 images and `flow_from_dataframe` takes ~2sec. Quite a big difference from what you reported, could you try to run it or maybe @Dref360 and report on how much time it takes?
I also added the profiler code if you run this in a Jupyter notebook. Indeed it takes ~87% of the time in the validation function, but that is spread out evenly (~32%) between 
```
filepaths = df[x_col].map(
    lambda fname: os.path.join(self.directory or '', fname)
)
 format_check = filepaths.map(get_extension).isin(self.white_list_formats)
 existence_check = filepaths.map(os.path.isfile)
```
Here the minimal example.
```
!python -m pip install line_profiler
%load_ext line_profiler

import os
import pandas as pd
from keras_preprocessing.image import DataFrameIterator
from keras_preprocessing.image import ImageDataGenerator


filenames = set()

N = 10000
for folder0 in ['', 'test0', 'test1']:
    for folder1 in ['', 'test2', 'test3']:
        for folder2 in ['', 'test4', 'test5']:
            for i in range(N):
                file = os.path.join('/tmp', folder0, folder1, folder2, f'{i}.jpg')
                filenames.add(file)
                os.makedirs(os.path.dirname(file), exist_ok=True)
                open(file, 'w').close()
                
df = pd.DataFrame({'filename': list(filenames)})

gen = ImageDataGenerator()
%timeit gen.flow_from_dataframe(df, class_mode='input')
%lprun -f DataFrameIterator.__init__ gen.flow_from_dataframe(df, class_mode='input')
%lprun -f DataFrameIterator._filter_valid_filepaths gen.flow_from_dataframe(df, class_mode='input')
```
It would be helpful to first reproduce the problem.

**Comment by Dref360** [comment]
As @jkthompson said, the issue could arise when we use remote file server with high latency.

**Comment by rragundez** [comment]
@qinst64 are the values you reported in the issue description also based on remote server execution?

**Comment by qinst64** [comment]
@rragundez This is my result on 270000 files:
```
%timeit gen.flow_from_dataframe(df, class_mode='input')
#37.2 s ± 41.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

%lprun -f DataFrameIterator.__init__ gen.flow_from_dataframe(df, class_mode="input")
#99.2%     df = self._filter_valid_filepaths(df, x_col)

%lprun -f DataFrameIterator._filter_valid_filepaths gen.flow_from_dataframe(df, class_mode="input")
# 2.8%    format_check = filepaths.map(get_extension).isin(self.white_list_formats)
#91.1%    existence_check = filepaths.map(os.path.isfile)
# 0.0%    return df[format_check & existence_check]

```
For detail, my 150K images were under two folders (no other images, as to bench against `flow_from_directory`) on the computer (win10, SSD) itself, below are results on from `localhost:8888`:
```
%%time
flow = ImageDataGenerator().flow_from_directory(dir)
# this takes 5.8s

%%time
flow = ImageDataGenerator().flow_from_dataframe(df, class_mode="input")
#this takes 23.6s (strangely, today it runs 7s faster, maybe affected by other running programs)

%%time
flow = ImageDataGenerator().flow_from_dataframe(df, **param)
#without _filter_valid_filepaths this takes 0.5s

%%time
files = list(Path(dir).rglob("*.jpg"))
#listing all 150K files, this takses 2.3s

%%time
files  = []
for (dirpath, dirnames, filenames) in walk(dir):
    files.extend(filenames)
#listing all 150K files, this takses 0.5s

%%time
r = list(map(os.path.isfile, files))
#this takes 10.6s

df = pd.Series(files)
%%time
r = df.map(os.path.isfile)
#this takes 10.6s
```

**Comment by rragundez** [comment]
thanks for the extra info @qinst64, unfortunately the comparison you make are not fair for the use case, for example 
- Your `rglob` example works only for a single extension (it does not accept a regex pattern that we could use for all extensions)
- The `walk` example only returns the filenames but not the full paths, so in order to cross reference with the paths in the dataframe there has to be at least one more pass on the data. Also it might be that that dir used searches in subdirectories which are not included in the filepaths of the dataframe, slowing down the execution unnecessarily and impacting memory. For example is `dir='/'` (same thing for rglob)

I also make these tests:

```
white_list_formats = ('jpg', 'png')
import os
import pandas as pd
from keras_preprocessing.image import DataFrameIterator
from keras_preprocessing.image import ImageDataGenerator


filenames = set()

N = 1000
for folder0 in ['', 'test0', 'test1']:
    for folder1 in ['', 'test2', 'test3']:
        for folder2 in ['', 'test4', 'test5']:
            for i in range(N):
                file = os.path.join('/tmp', folder0, folder1, folder2, f'{i}.jpg')
                filenames.add(file)
                os.makedirs(os.path.dirname(file), exist_ok=True)
                open(file, 'w').close()
                
paths_df = pd.DataFrame({'filename': list(filenames)})
paths_df['dummy'] = 0
print(len(paths_df))

def get_extension(filename):
    return os.path.splitext(filename)[1].strip('.').lower()

def _validate(filename, white_list_formats):
    return filename.endswith(white_list_formats) and os.path.isfile(filename)

def _filter_valid_filepaths_0(df, x_col, directory, white_list_formats):
    filepaths = df[x_col].map(
        lambda fname: os.path.join(directory or '', fname)
    )
    format_check = filepaths.map(get_extension).isin(white_list_formats)
    existence_check = filepaths.map(os.path.isfile)
    return df[format_check & existence_check]


def _filter_valid_filepaths_1(df, x_col, directory, white_list_formats):
    filepaths = df[x_col].map(
        lambda fname: os.path.join(directory or '', fname)
    )
    return df[filepaths.map(lambda x: _validate(x, white_list_formats))]

def validate_via_grouping_0(df):
    valid_filenames = set(filename for filename in glob.glob(df.name + '/*') if filename.endswith(white_list_formats))
    return df.query("filename in @valid_filenames")

def validate_via_grouping_1(df):
    valid_filenames = set(filename for filename in os.listdir(df.name) if filename.endswith(white_list_formats))
    return df.query("filename in @valid_filenames")


%timeit _filter_valid_filepaths_0(paths_df, 'filename', '', white_list_formats) # 14.6 ms
%timeit _filter_valid_filepaths_1(paths_df, 'filename', '', white_list_formats) # 10 ms
%timeit paths_df.set_index('filename').groupby(lambda x: os.path.dirname(x), as_index=False).apply(validate_via_grouping_0).reset_index('filename') # 5.9 s
%timeit paths_df.set_index('filename').groupby(lambda x: os.path.dirname(x), as_index=False).apply(validate_via_grouping_1).reset_index('filename') # 2.29 s
```
So still the use of `os.path.isfile` is the fastest option. I have to say I don't see how to satisfy the checking cases we have and at the same time make it fast. 

The only solution I see is indeed adding that parameters of validation and let the user decide. This brings other drawbacks of course: Should we just let it crash if images are invalid? or should we include try catch everywhere this could happen because of invalid images? or should we just stress a big warning on this parameters docstring that if no validation is done it just continues with the possibility of crashing? 

BTW regardless of that parameter or not I agree that there should be a warning if there are invalid filenames in the dataframe. There is also a decision here (I encountered something similar before in Sklearn) do we just say there are invalid images? do we say why they are invalid? and do we risk overflowing the users output with a warningor mention of each filename that is not valid? I would prefer the simple warning stating there are invalid images in the dataframe.

**Comment by rragundez** [comment]
I created this PR https://github.com/keras-team/keras-preprocessing/pull/177
Still have to add the tests but please let me know what you think.

**Comment by jkthompson** [comment]
I like this approach.  I added a few small comments on the PR.

**Comment by SteveStrongBAH** [comment]
is this fixed?   I just updated PIP using requirements.txt
