### ISSUE TITLE
ImageDagaGenerator sometimes returns mismatched img/mask

### ISSUE THREAD

**Issue by Adman** [keras-team/keras-preprocessing#236]
Hello, I'm working on image segmentation and using 1keras_preprocessing 1.0.2` and `keras 2.2.2`. When I'm trying to feed the model with ImageDataGenerator and do horizontal flip augmentation, sometimes the image is flipped and the mask is being kept unchanged. This happens with batch size = 2, but with batch size = 1 the issue does not occur. Could you give me an advice on how to fix that? Thanks

- [x] Check that you are up-to-date with the master branch of keras-preprocessing. You can update with:
`pip install git+git://github.com/keras-team/keras-preprocessing.git --upgrade --no-deps`

```python
def train_generator(batch_size, train_path, image_folder, mask_folder,
                    img_target_size=(480, 640), augs={}, tohsv=False):
    image_datagen = ImageDataGenerator(**augs)
    masks_datagen = ImageDataGenerator(**augs)

    image_generator = image_datagen.flow_from_directory(
        train_path,
        class_mode=None,
        classes=[image_folder],
        color_mode='rgb',
        target_size=img_target_size,
        batch_size=batch_size,
        seed=1
    )   

    mask_generator = masks_datagen.flow_from_directory(
        train_path,
        class_mode=None,
        classes=[mask_folder],
        color_mode='grayscale',
        target_size=img_target_size,
        batch_size=batch_size,
        seed=1
    )

    generator = zip(image_generator, mask_generator) 
    for (img, mask) in generator:
        yield (img, mask)
```

**Comment by rragundez** [comment]
can you make a minimal reproducible example please? This means I should be able to run the example  without downloading anything and reproduce the behavior you are describing. Thanks

**Comment by Frost-Lee** [comment]
Basically same problem [here](https://stackoverflow.com/questions/58846552/keras-imagegenerator-image-and-mask-augments-differently).

**Comment by Frost-Lee** [comment]
Also observed the problem [here](https://stackoverflow.com/questions/58846552/keras-imagegenerator-image-and-mask-augments-differently), but I failed to reproduce this again. In your case, since `image_datagen` and `masks_datagen` are different `ImageDataGenerator` instances, they are supposed to behave differently when randomness is introduced, such as `horizontal_flip`, which use `np.random.random() < 0.5` to decide whether to flip (as [here](https://github.com/keras-team/keras-preprocessing/blob/28b8c9a57703b60ea7d23a196c59da1edf987ca0/keras_preprocessing/image/image_data_generator.py#L805-L806)).

I think the problem should be why the mismatch don't occur when batch size is 1?

**Comment by Adman** [comment]
@rragundez I fixed that by removing `validation_generator` and using simple `validation_data`.

**Comment by Adman** [comment]
But the problem still persists if someone uses `validation_generator`

**Comment by rragundez** [comment]
Hi Adman, Can you make a minimal reproducible example? Then I can take a closer look and re-open the issue.
