### ISSUE TITLE
Unable to get tests to use alterations to keras_preprocessing: contributor's guide needed

### ISSUE THREAD

**Issue by rjurney** [keras-team/keras-preprocessing#250]
I'm running master and I have altered the code for Tokenizer.fit_on_texts to add a parameter. I run the unit tests, and my edits have no effect. I tried installing the package and still my edits have no effect. A contributor's guide would be helpful, and if you tell me how to run the tests I will start one.

I am running the tests via pytest 5.1.1 in Anaconda Python on Mac OS X.

- [x] Check that you are up-to-date with the master branch of keras-preprocessing. You can update with:
`pip install git+git://github.com/keras-team/keras-preprocessing.git --upgrade --no-deps`

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by rragundez** [comment]
your installation of `keras-preprocessing` needs to point to the directory where your code is, not to an installed version of the package via `pip install keras` or so. In order to do that you need to `pip install -e .` in the  root folder of this repository. Then code executed will be picked up from the directory where you made your changes.

**Comment by rjurney** [comment]
Thanks
